---
- hosts: raspbian
  sudo: yes

  vars_files:
    - vars/main.yml

  tasks:
    # Note: Changes here require a reboot, but we don't do that now.
    - name: Copy over config.txt.
      template:
        src: templates/config.txt.j2
        dest: /boot/config.txt
        mode: 0755

    - name: Back up the network interfaces file.
      command: cp /etc/network/interfaces /tmp/network-interfaces

    - name: Set timezone.
      copy:
        content: "{{ locale_timezone }}"
        dest: /etc/timezone
        mode: 0644
        backup: yes
      notify: update timezone

    - name: Configure keyboard layout.
      template:
        src: templates/keyboard.j2
        dest: /etc/default/keyboard
        mode: 0644
      notify: update keyboard

    - name: Configure locale.
      template:
        src: templates/locale.j2
        dest: /etc/default/locale
        mode: 0644
      notify: update locale
      with_items:
        - { src: templates/locale.j2, dest: /etc/default/locale }
        - { src: templates/locale.gen.j2, dest: /etc/locale.gen }

    - name: Set up nameservers.
      template:
        src: templates/resolv.conf.j2
        dest: /etc/resolv.conf
        mode: 0644

    - name: Update apt cache.
      apt:
        update_cache: yes
        cache_valid_time: 900

    - name: Install needed packages.
      apt:
        name: "{{ item }}"
        state: present
      with_items: install_packages

    - name: Remove unneeded packages.
      apt:
        name: "{{ item }}"
        state: absent
        purge: yes
      register: apt_remove_packages
      with_items: remove_packages

    - name: Autoremove unused packages.
      command: apt-get -y autoremove
      when: apt_remove_packages.changed

    - name: Update all remaining packages.
      apt:
        update_cache: yes
        cache_valid_time: 900
        upgrade: safe

    - name: Ensure certain files and directories are deleted.
      file:
        path: "{{ item }}"
        state: absent
      with_items: remove_paths

    - name: Restore the network interfaces file.
      command: cp /tmp/network-interfaces /etc/network/interfaces

    - name: Clean apt caches.
      command: apt-get clean

    - name: Clear out all logs.
      shell: "find /var/log -type f -exec /bin/cp /dev/null {} \\;"

    - name: Disable swap and remove swap file.
      command: "{{ item }}"
      with_items:
        - swapoff -a
        - sudo rm -f /var/swap
        - sudo dd if=/dev/zero of=/zerofile bs=1M count=1024
        - rm -f /zerofile

  handlers:
    - include: handlers/main.yml
